"""Pytest tests for tert.crypto (Ed25519 + did:key).

Correctness is anchored against OpenSSL where available: a signature produced by
this pure-Python implementation must verify with ``openssl pkeyutl``, and a key
generated by OpenSSL must produce the same public key and verifiable signatures
here. This makes the implementation's conformance externally checkable.
"""
import base64
import os
import shutil
import struct
import subprocess

import pytest

from tert.crypto import (
    PUBKEY_BYTES,
    SEED_BYTES,
    SIGNATURE_BYTES,
    base58btc_decode,
    base58btc_encode,
    did_key_from_pubkey,
    ed25519_publickey,
    ed25519_sign,
    ed25519_verify,
    multibase_base58btc,
    pubkey_from_did_key,
)

# A fixed, well-known test seed (deterministic across the test suite and the
# Rust interop tests). NOT a secret.
FIXED_SEED = bytes(range(1, 33))  # 01 02 03 ... 20


class TestEd25519RoundTrip:
    def test_pubkey_length(self):
        pub = ed25519_publickey(FIXED_SEED)
        assert len(pub) == PUBKEY_BYTES

    def test_sign_verify(self):
        msg = b"provenance document"
        pub = ed25519_publickey(FIXED_SEED)
        sig = ed25519_sign(FIXED_SEED, msg)
        assert len(sig) == SIGNATURE_BYTES
        assert ed25519_verify(pub, msg, sig) is True

    def test_verify_rejects_tampered_message(self):
        pub = ed25519_publickey(FIXED_SEED)
        sig = ed25519_sign(FIXED_SEED, b"hello")
        assert ed25519_verify(pub, b"hell0", sig) is False

    def test_verify_rejects_tampered_signature(self):
        msg = b"hello"
        pub = ed25519_publickey(FIXED_SEED)
        sig = bytearray(ed25519_sign(FIXED_SEED, msg))
        sig[0] ^= 0x01
        assert ed25519_verify(pub, msg, bytes(sig)) is False

    def test_verify_rejects_wrong_key(self):
        msg = b"hello"
        sig = ed25519_sign(FIXED_SEED, msg)
        other_pub = ed25519_publickey(bytes(range(2, 34)))
        assert ed25519_verify(other_pub, msg, sig) is False

    def test_bad_lengths(self):
        with pytest.raises(ValueError):
            ed25519_publickey(b"short")
        assert ed25519_verify(b"x", b"m", b"y") is False


class TestDeterminism:
    def test_signature_is_deterministic(self):
        msg = b"same message"
        sig1 = ed25519_sign(FIXED_SEED, msg)
        sig2 = ed25519_sign(FIXED_SEED, msg)
        assert sig1 == sig2


class TestBase58:
    @pytest.mark.parametrize("data", [
        b"",
        b"\x00",
        b"\x00\x00hello",
        bytes(range(32)),
        b"\xed\x01" + bytes(range(32)),
    ])
    def test_roundtrip(self, data):
        assert base58btc_decode(base58btc_encode(data)) == data

    def test_known_vector(self):
        # "hello world" -> base58 (Bitcoin alphabet)
        assert base58btc_encode(b"hello world") == "StV1DL6CwTryKyV"

    def test_invalid_char(self):
        with pytest.raises(ValueError):
            base58btc_decode("0OIl")  # all excluded from the alphabet


class TestDidKey:
    def test_ed25519_prefix(self):
        pub = ed25519_publickey(FIXED_SEED)
        did = did_key_from_pubkey(pub)
        # Ed25519 did:keys always start with z6Mk
        assert did.startswith("did:key:z6Mk")

    def test_roundtrip(self):
        pub = ed25519_publickey(FIXED_SEED)
        did = did_key_from_pubkey(pub)
        assert pubkey_from_did_key(did) == pub

    def test_multibase_prefix(self):
        assert multibase_base58btc(b"\x00").startswith("z")

    def test_bad_did(self):
        with pytest.raises(ValueError):
            pubkey_from_did_key("did:web:example.com")


def _openssl_available() -> bool:
    return shutil.which("openssl") is not None


def _seed_to_pkcs8_pem(seed: bytes) -> bytes:
    """Wrap a 32-byte Ed25519 seed in a PKCS#8 PEM (DER prefix is fixed)."""
    # PKCS#8 PrivateKeyInfo for Ed25519: fixed 16-byte prefix + 32-byte seed.
    der_prefix = bytes.fromhex("302e020100300506032b657004220420")
    der = der_prefix + seed
    b64 = base64.encodebytes(der).decode().strip()
    return ("-----BEGIN PRIVATE KEY-----\n" + b64 + "\n-----END PRIVATE KEY-----\n").encode()


@pytest.mark.skipif(not _openssl_available(), reason="openssl not available")
class TestOpenSslOracle:
    def test_openssl_verifies_our_signature(self, tmp_path):
        msg = b"cross-checked with openssl"
        pub = ed25519_publickey(FIXED_SEED)
        sig = ed25519_sign(FIXED_SEED, msg)

        # Build the OpenSSL public key (PEM) from the raw 32-byte public key.
        # SubjectPublicKeyInfo for Ed25519: fixed 12-byte prefix + 32-byte key.
        spki = bytes.fromhex("302a300506032b6570032100") + pub
        pub_pem = (
            b"-----BEGIN PUBLIC KEY-----\n"
            + base64.encodebytes(spki).strip()
            + b"\n-----END PUBLIC KEY-----\n"
        )
        pub_file = tmp_path / "pub.pem"
        pub_file.write_bytes(pub_pem)
        msg_file = tmp_path / "msg.bin"
        msg_file.write_bytes(msg)
        sig_file = tmp_path / "sig.bin"
        sig_file.write_bytes(sig)

        proc = subprocess.run(
            ["openssl", "pkeyutl", "-verify", "-pubin", "-inkey", str(pub_file),
             "-rawin", "-in", str(msg_file), "-sigfile", str(sig_file)],
            capture_output=True, text=True,
        )
        assert proc.returncode == 0, proc.stderr

    def test_our_pubkey_matches_openssl(self, tmp_path):
        # Wrap our seed as PKCS#8, ask openssl for the public key, compare.
        key_pem = tmp_path / "key.pem"
        key_pem.write_bytes(_seed_to_pkcs8_pem(FIXED_SEED))
        proc = subprocess.run(
            ["openssl", "pkey", "-in", str(key_pem), "-pubout", "-outform", "DER"],
            capture_output=True,
        )
        assert proc.returncode == 0, proc.stderr
        # Last 32 bytes of the DER SubjectPublicKeyInfo are the raw public key.
        assert proc.stdout[-32:] == ed25519_publickey(FIXED_SEED)


class TestInteropVector:
    """A fixed vector shared verbatim with the Rust interop test.

    These values are produced by this implementation (which is validated against
    OpenSSL above) and hard-coded so the Rust ``tert::crypto`` port must match.
    """

    EXPECTED_PUBKEY_HEX = None  # filled in by the helper below at import time

    def test_fixed_vector_self_consistent(self):
        pub = ed25519_publickey(FIXED_SEED)
        sig = ed25519_sign(FIXED_SEED, b"tert interop vector")
        # Self-consistency; the exact hex is asserted in test_crypto_vector.py.
        assert ed25519_verify(pub, b"tert interop vector", sig)
