"""Test Execution Report Tracker (tert) - Python package."""

__version__ = "0.1.0"
__author__ = "westurner"

from .shellwrap import Shellwrap
from .crypto import (
    ed25519_publickey,
    ed25519_sign,
    ed25519_verify,
    did_key_from_pubkey,
    pubkey_from_did_key,
)
from .did_agent import (
    DidAgent,
    DidAgentClient,
    DidAgentServer,
    DidAgentError,
)
from .vc import (
    canonicalize,
    sign_document,
    verify_document,
    get_cryptosuite,
    CRYPTOSUITES,
    CryptosuiteError,
    DEFAULT_CRYPTOSUITE,
)
from .fetch import (
    CryptoConfig,
    FetchResult,
    FetchError,
    CurlStrategy,
    WgetStrategy,
    RustStrategy,
    get_strategy,
    fetch,
    verify_crypto_config,
    discover_ca_bundle,
    KeyBackend,
    AgentKeyBackend,
    FileKeyBackend,
    resolve_key_backend,
    build_provenance,
    sign_provenance,
    verify_provenance,
    verify_provenance_file,
)
from .run_tests import (
    ReplogDB,
    TertTestRun,
    TertTestRunner,
    PytestRunner,
    CargoRunner,
    GoRunner,
    JestRunner,
    VitestRunner,
    ToxRunner,
    get_runner,
    run_tests,
    query_runs,
    query_artifacts,
    query_coverage_lines,
)

__all__ = [
    "Shellwrap",
    "ed25519_publickey",
    "ed25519_sign",
    "ed25519_verify",
    "did_key_from_pubkey",
    "pubkey_from_did_key",
    "DidAgent",
    "DidAgentClient",
    "DidAgentServer",
    "DidAgentError",
    "canonicalize",
    "sign_document",
    "verify_document",
    "get_cryptosuite",
    "CRYPTOSUITES",
    "CryptosuiteError",
    "DEFAULT_CRYPTOSUITE",
    "CryptoConfig",
    "FetchResult",
    "FetchError",
    "CurlStrategy",
    "WgetStrategy",
    "RustStrategy",
    "get_strategy",
    "fetch",
    "verify_crypto_config",
    "discover_ca_bundle",
    "KeyBackend",
    "AgentKeyBackend",
    "FileKeyBackend",
    "resolve_key_backend",
    "build_provenance",
    "sign_provenance",
    "verify_provenance",
    "verify_provenance_file",
    "ReplogDB",
    "TertTestRun",
    "TertTestRunner",
    "PytestRunner",
    "CargoRunner",
    "GoRunner",
    "JestRunner",
    "VitestRunner",
    "ToxRunner",
    "get_runner",
    "run_tests",
    "query_runs",
    "query_artifacts",
    "query_coverage_lines",
]
