#!/usr/bin/env python3
"""
Run commands and display streaming terminal output with colors
and also write to a log file with ANSI-escape-characters removed.
"""
import subprocess
import re
import argparse
import sys
import os
import threading
import pty
import fcntl
import struct
import signal
import select
import shutil
import termios
import tty
from pathlib import Path
from typing import List, Optional, Tuple


class Shellwrap:
    """Execute commands with color streaming and dual logging."""
    
    ANSI_ESCAPE_PATTERN = re.compile(r'\x1b\[[0-9;]*[a-zA-Z]')
    
    def __init__(
        self,
        log_file: str = "build.log",
        log_file_ansi: str = "build.log.ansi",
        keep_ansi: bool = False,
        trace: bool = True,
        color_mode: str = "auto",
        shell: Optional[str] = None,
        use_bash_env: bool = False,
        bash_env_file: Optional[str] = None,
        interactive_shell: bool = False
    ):
        self.log_file = log_file
        self.log_file_ansi = log_file_ansi
        self.keep_ansi = keep_ansi
        self.trace = trace
        self.color_mode = color_mode  # auto, always, or never
        self.shell = shell  # bash, zsh, or full path - None means don't use interactive shell
        self.interactive_shell = interactive_shell  # Whether to use -i flag for interactive mode
        self.use_bash_env = use_bash_env
        self.bash_env_file = bash_env_file or os.path.expanduser("~/.shellwrap_aliases.sh")
        self.commands: List[str] = []
        self.argv: List[str] = []
    
    def set_color_env(self) -> None:
        """Set environment variables for colored output across tools."""
        # Determine if colors should be used based on color_mode
        use_colors = False
        
        if self.color_mode == "always":
            use_colors = True
        elif self.color_mode == "auto":
            # Use colors only if stdout is a TTY
            use_colors = sys.stdout.isatty()
        elif self.color_mode == "never":
            use_colors = False
        
        if use_colors:
            os.environ.setdefault("CARGO_TERM_COLOR", "always")
            os.environ.setdefault("FORCE_COLOR", "1")
            os.environ.setdefault("PYTEST_ADDOPTS", "--color=yes")
        else:
            # Clear color variables if colors are disabled
            os.environ["NO_COLOR"] = "1"
            os.environ.pop("FORCE_COLOR", None)
            os.environ.pop("CARGO_TERM_COLOR", None)
    
    def strip_ansi(self, text: str) -> str:
        """Remove ANSI escape sequences from text."""
        return self.ANSI_ESCAPE_PATTERN.sub('', text)
    
    def _setup_bash_env(self) -> None:
        """Create BASH_ENV file with safe permissions (600) for alias injection."""
        if not self.use_bash_env:
            return
        
        try:
            # Create BASH_ENV file with shopt expand_aliases and ls alias for colors
            content = """#!/bin/bash
# Auto-generated by shellwrap for color alias injection
shopt -s expand_aliases
alias ls='ls --color=always'
alias grep='grep --color=always'
alias diff='diff --color=always'
alias tree='tree -C'
"""
            
            # Write file (will fail safely if permissions don't allow)
            with open(self.bash_env_file, 'w') as f:
                f.write(content)
            
            # Set safe permissions: readable/writable only by owner (600)
            os.chmod(self.bash_env_file, 0o600)
            
            if self.trace:
                print(f"[shellwrap] Created BASH_ENV at {self.bash_env_file} with permissions 600", file=sys.stderr)
        
        except Exception as e:
            if self.trace:
                print(f"[shellwrap] Warning: Could not setup BASH_ENV: {e}", file=sys.stderr)
    
    def _get_shell_command(self, cmd: str) -> Tuple[str, List[str]]:
        """Get the shell executable and command with appropriate flags.
        
        Returns: (shell_exe, shell_args_list)
        """
        # Resolve shell path (default to bash if not specified)
        shell_name = self.shell or "bash"
        
        if shell_name.startswith("/"):
            shell_exe = shell_name
        elif shell_name == "bash":
            shell_exe = "/bin/bash"
        elif shell_name == "zsh":
            shell_exe = "/bin/zsh"
        else:
            shell_exe = shutil.which(shell_name) or shell_name
        
        # Build shell args with optional -i flag for interactive mode (loads aliases)
        shell_args = [shell_exe]
        if self.interactive_shell:
            shell_args.append("-i")
        shell_args.extend(["-c", cmd])
        
        return shell_exe, shell_args
    
    def print_colors(self) -> int:
        """Print ANSI color test patterns to stdout."""
        # Basic colors
        colors = {
            "Black": "30",
            "Red": "31",
            "Green": "32",
            "Yellow": "33",
            "Blue": "34",
            "Magenta": "35",
            "Cyan": "36",
            "White": "37",
        }
        
        # Attributes
        attributes = {
            "Normal": "0",
            "Bold": "1",
            "Dim": "2",
            "Italic": "3",
            "Underline": "4",
        }
        
        print("\n=== ANSI Color Test ===\n")
        
        # Print basic colors
        print("Basic Colors:")
        for name, code in colors.items():
            print(f"  \x1b[{code}m{name}\x1b[0m")
        
        print("\nBold Colors:")
        for name, code in colors.items():
            print(f"  \x1b[1;{code}m{name}\x1b[0m")
        
        print("\nAttributes:")
        for name, code in attributes.items():
            print(f"  \x1b[{code}m{name}\x1b[0m")
        
        print("\n256-Color Mode:")
        print("  \x1b[38;5;196mRed (196)\x1b[0m", end="  ")
        print("  \x1b[38;5;82mGreen (82)\x1b[0m", end="  ")
        print("  \x1b[38;5;21mBlue (21)\x1b[0m")
        
        print("\nRGB Colors (if supported):")
        print("  \x1b[38;2;255;0;0mRed\x1b[0m", end="  ")
        print("  \x1b[38;2;0;255;0mGreen\x1b[0m", end="  ")
        print("  \x1b[38;2;0;0;255mBlue\x1b[0m")
        
        print("\n=== End Color Test ===\n")
        return 0
    
    def execute(self) -> int:
        """Execute all commands and manage logging."""
        ansi_output = []
        exit_code = 0
        
        try:
            try:
                for cmd in self.commands:
                    if self.trace:
                        print(f"+ {cmd}", file=sys.stderr)
                    
                    # Execute command with shell=True to handle command strings
                    process = subprocess.Popen(
                        cmd,
                        shell=True,
                        stdout=subprocess.PIPE,
                        stderr=subprocess.STDOUT,
                        text=True,
                        bufsize=1  # Line buffered for streaming
                    )
                    
                    # Stream output to stdout and collect for logging
                    if process.stdout:
                        for line in process.stdout:
                            sys.stdout.write(line)
                            sys.stdout.flush()
                            ansi_output.append(line)
                    
                    exit_code = process.wait()
                    if exit_code != 0:
                        break
            
            except KeyboardInterrupt:
                print("\nshellwrap: interrupted by user", file=sys.stderr)
                exit_code = 130  # Standard exit code for SIGINT
            
            except Exception as e:
                print(f"shellwrap: error: {e}", file=sys.stderr)
                exit_code = 1
        
        finally:
            # Always write logs, regardless of what happened
            try:
                # Write ANSI log file
                ansi_content = ''.join(ansi_output)
                with open(self.log_file_ansi, 'w') as f:
                    f.write(ansi_content)
                
                # Create plain log (ANSI-stripped)
                plain_content = self.strip_ansi(ansi_content)
                with open(self.log_file, 'w') as f:
                    f.write(plain_content)
                
                # Optionally remove ANSI log
                if not self.keep_ansi:
                    Path(self.log_file_ansi).unlink(missing_ok=True)
            
            except Exception as e:
                print(f"shellwrap: error writing logs: {e}", file=sys.stderr)
                # Set exit code to 1 if log writing fails and command succeeded
                if exit_code == 0:
                    exit_code = 1
        
        return exit_code
    
    def execute_streaming(self, use_fallback: bool = False) -> int:
        """Execute with real-time log streaming to both files (simplified version)."""
        if use_fallback:
            return self.execute()
        return self._execute_streaming_pipe()
    
    def _execute_streaming_pipe(self) -> int:
        """Execute with pipes (standard streaming mode)."""
        exit_code = 0
        log_lock = threading.Lock()
        
        if self.use_bash_env:
            self._setup_bash_env()
        
        try:
            try:
                for i_cmd, cmd in enumerate(self.commands):
                    if self.trace:
                        print(f"+ {cmd}", file=sys.stderr)
                    
                    mode = 'a' if i_cmd > 0 else 'w'
                    
                    if self.shell:
                        shell_exe, shell_args = self._get_shell_command(cmd)
                        popen_args = shell_args
                        popen_kwargs = {
                            "stdout": subprocess.PIPE,
                            "stderr": subprocess.PIPE,
                            "text": True,
                            "bufsize": 1
                        }
                        if self.use_bash_env and ("bash" in shell_exe or self.shell == "bash"):
                            env = os.environ.copy()
                            env["BASH_ENV"] = self.bash_env_file
                            popen_kwargs["env"] = env
                    else:
                        popen_args = cmd
                        popen_kwargs = {
                            "shell": True,
                            "stdout": subprocess.PIPE,
                            "stderr": subprocess.PIPE,
                            "text": True,
                            "bufsize": 1
                        }
                    
                    process = subprocess.Popen(popen_args, **popen_kwargs)
                    
                    with open(self.log_file_ansi, mode) as ansi_f, \
                         open(self.log_file, mode) as plain_f:
                        
                        def stream_output(pipe, is_stderr=False):
                            if pipe is None:
                                return
                            for line in pipe:
                                with log_lock:
                                    try:
                                        if is_stderr:
                                            sys.stderr.write(line)
                                        else:
                                            sys.stdout.write(line)
                                        sys.stdout.flush() if not is_stderr else sys.stderr.flush()
                                        if not ansi_f.closed:
                                            ansi_f.write(line)
                                            ansi_f.flush()
                                        if not plain_f.closed:
                                            plain_line = self.strip_ansi(line)
                                            plain_f.write(plain_line)
                                            plain_f.flush()
                                    except ValueError:
                                        # File closed, stop writing
                                        return
                        
                        stdout_thread = threading.Thread(
                            target=stream_output,
                            args=(process.stdout, False),
                            daemon=False
                        )
                        stderr_thread = threading.Thread(
                            target=stream_output,
                            args=(process.stderr, True),
                            daemon=False
                        )
                        
                        stdout_thread.start()
                        stderr_thread.start()
                        exit_code = process.wait()
                        
                        # Wait for threads to finish before closing files
                        stdout_thread.join(timeout=5)
                        stderr_thread.join(timeout=5)
                        stdout_thread.join(timeout=5.0)
                        stderr_thread.join(timeout=5.0)
                        
                        if exit_code != 0:
                            break
            
            except KeyboardInterrupt:
                print("\nshellwrap: interrupted by user", file=sys.stderr)
                exit_code = 130
            except Exception as e:
                print(f"shellwrap: error: {e}", file=sys.stderr)
                exit_code = 1
        
        finally:
            try:
                if not self.keep_ansi:
                    Path(self.log_file_ansi).unlink(missing_ok=True)
            except Exception as e:
                print(f"shellwrap: error cleaning up: {e}", file=sys.stderr)
                if exit_code == 0:
                    exit_code = 1
        
        return exit_code
    
    @staticmethod
    def parse_args(args: Optional[List[str]] = None) -> argparse.Namespace:
        """Parse command-line arguments."""
        parser = argparse.ArgumentParser(
            prog='shellwrap',
            description='Run commands with color streaming and dual logging',
            add_help=False
        )
        parser.add_argument('-h', '--help', action='store_true')
        parser.add_argument('--self-test', action='store_true')
        parser.add_argument('--print-colors', action='store_true')
        parser.add_argument('--color', choices=['auto', 'always', 'never'], 
                            default='auto', dest='color_mode')
        parser.add_argument('--shell', default=None, dest='shell')
        parser.add_argument('--bash-env', action='store_true', dest='use_bash_env')
        parser.add_argument('-i', '--interactive', action='store_true', dest='interactive_shell', default=False)
        parser.add_argument('--keep-ansi', action='store_true', dest='keep_ansi', default=None)
        parser.add_argument('--no-keep-ansi', action='store_false', dest='keep_ansi')
        parser.add_argument('--log-file', default=None, dest='log_file')
        parser.add_argument('--log-file-ansi', default=None, dest='log_file_ansi')
        parser.add_argument('-c', action='append', dest='commands', default=[])
        parser.add_argument('--', dest='explicit_argv', action='store_true')
        parser.add_argument('cmdstr', nargs='?', default=None)
        parser.add_argument('argv', nargs='*', default=[])
        
        if args is None:
            args = sys.argv[1:]
        
        if '--' in args:
            explicit_idx = args.index('--')
            explicit_argv = args[explicit_idx + 1:]
            args = args[:explicit_idx]
        else:
            explicit_argv = []
        
        parsed = parser.parse_args(args)
        parsed.explicit_argv_list = explicit_argv
        
        if parsed.interactive_shell and parsed.shell is None:
            parsed.use_bash_env = True
        
        return parsed


def main() -> int:
    """Main entry point."""
    args = Shellwrap.parse_args()
    
    if args.help:
        print("Usage: shellwrap [--help] [--color auto|always|never] [-c cmdstr]")
        return 0
    
    if args.print_colors:
        sw = Shellwrap(color_mode=args.color_mode, shell=args.shell, use_bash_env=args.use_bash_env, interactive_shell=args.interactive_shell)
        return sw.print_colors()
    
    # Determine keep_ansi: explicit CLI arg takes precedence, then env var, then default to True
    if args.keep_ansi is not None:
        keep_ansi = args.keep_ansi
    else:
        keep_ansi = os.environ.get('KEEP_ANSI_LOG', '1') == '1'  # default to True if not set
    
    sw = Shellwrap(
        log_file=args.log_file or os.environ.get('LOG_FILE', 'build.log'),
        log_file_ansi=args.log_file_ansi or os.environ.get('LOG_FILE_ANSI', 'build.log.ansi'),
        keep_ansi=keep_ansi,
        trace=os.environ.get('TRACE', '1') == '1',
        color_mode=args.color_mode,
        shell=args.shell,
        use_bash_env=args.use_bash_env,
        interactive_shell=args.interactive_shell
    )
    sw.set_color_env()
    
    if args.commands:
        sw.commands = args.commands
    elif args.explicit_argv_list:
        sw.commands = [' '.join(args.explicit_argv_list)]
    elif args.cmdstr:
        sw.commands = [args.cmdstr]
    else:
        print("shellwrap: error: no command specified", file=sys.stderr)
        return 2
    
    return sw.execute_streaming()


if __name__ == '__main__':
    sys.exit(main())
